# Generated by Django 5.1.1 on 2024-09-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        db_comment="스케쥴 내용",
                        help_text="스케쥴 내용",
                        null=True,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_comment="스케쥴 날짜", db_index=True, help_text="스케쥴 날짜"
                    ),
                ),
                (
                    "start_time",
                    models.PositiveSmallIntegerField(
                        db_comment="시작 시간", help_text="시작 시간"
                    ),
                ),
                (
                    "end_time",
                    models.PositiveSmallIntegerField(
                        db_comment="시작 시간", help_text="시작 시간"
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
                "db_table": "schedule_event",
                "db_table_comment": "Schedules",
                "ordering": ["id"],
            },
        ),
    ]
