# Generated by Django 5.1.1 on 2024-09-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="이벤트 제목",
                        help_text="이벤트 제목",
                        max_length=255,
                    ),
                ),
                (
                    "content",
                    models.TextField(db_comment="이벤트 내용", help_text="이벤트 내용"),
                ),
                (
                    "is_all_day",
                    models.DateField(
                        db_comment="하루 종일 지속되는 이벤트인지 나타내는 값",
                        help_text="하루 종일 지속되는 이벤트인지 나타내는 값",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        db_comment="이벤트 시작 시간",
                        db_index=True,
                        help_text="이벤트 시작 시간",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        db_comment="이벤트 종료 시간. 하루종일 이벤트의 경우 null",
                        help_text="이벤트 종료 시간. 하루종일 이벤트의 경우 null",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "schedule_event",
                "db_table_comment": "Scheduled events",
                "ordering": ["id"],
            },
        ),
    ]
