# Generated by Django 5.1.1 on 2024-09-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="is_all_day",
            field=models.BooleanField(
                db_comment="하루 종일 지속되는 이벤트인지 나타내는 값",
                help_text="하루 종일 지속되는 이벤트인지 나타내는 값",
            ),
        ),
    ]
