# Generated by Django 5.1.1 on 2024-09-22 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="owner",
            field=models.ForeignKey(
                db_comment="Owner of the schedule",
                default=1,
                help_text="Owner of the schedule",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
            preserve_default=False,
        ),
    ]
